config/routes.rb
TLF::Application.routes.draw do
  username_h = { :username => %r([^/]+) }
  
  root :to => "forums#index"
  
  get   "search" => "forums#search", :as => :search
  
  get   "forums"                 => "admin#forums",   :as => :forums
  post  "forums/sort"            => "forums#sort",    :as => :sort_forums
  get   "forum/:id(/page/:page)" => "forums#show",    :as => :show_forum
  get   "forums/new"             => "forums#new",     :as => :new_forum  
  post  "forums/create"          => "forums#create",  :as => :create_forum
  get   "forum/:id/edit"         => "forums#edit",    :as => :edit_forum
  put   "forum/:id/update"       => "forums#update",  :as => :update_forum
  match "forum/:id/destroy"      => "forums#destroy", :as => :destroy_forum
  
  get   "thread/:id(/page/:page)"       => "threads#show",    :as => :show_thread
  get   "forum/:forum_id/thread/new"    => "threads#new",     :as => :new_thread
  post  "forum/:forum_id/thread/create" => "threads#create",  :as => :create_thread
  get   "thread/:id/edit"               => "threads#edit",    :as => :edit_thread
  put   "thread/:id/update"             => "threads#update",  :as => :update_thread
  get   "thread/:id/destroy"            => "threads#destroy", :as => :destroy_thread

  get   "posts(/:username(/page/:page))"             => "posts#index",   :as => :posts  
  get   "thread/:thread_id/post/new(/quote/:sub_id)" => "posts#new",     :as => :new_post
  post  "thread/:thread_id/post/create"              => "posts#create",  :as => :create_post
  get   "thread/:thread_id/post/:id/edit"            => "posts#edit",    :as => :edit_post
  put   "thread/:thread_id/post/:id/update"          => "posts#update",  :as => :update_post
  get   "post/:id/destroy"                           => "posts#destroy", :as => :destroy_post
  get   "post/:id/nuke"                              => "posts#nuke",    :as => :nuke_post

  get   "register"               => "users#new",               :as => :new_user
  post  "users/create"           => "users#create",            :as => :create_user
  get   "user/:id/activate/:key" => "users#activate",          :as => :activate_user
  match "request_password"       => "users#request_password",  :as => :request_password
  get   "user/:id/recover/:key"  => "users#recover_password",  :as => :recover_password
  get   "user/:id/resend"        => "users#resend_activation", :as => :resend_activation
  
  match "login"  => "sessions#new",     :as => :login
  get   "logout" => "sessions#destroy", :as => :logout

  get   "profile/:username" => "users#show",   :as => :show_profile, :constraints => username_h
  get   "myprofile/edit"    => "users#edit",   :as => :edit_profile
  put   "myprofile/update"  => "users#update", :as => :update_profile

  get   "users"                => "users#index",           :as => :users
  get   "user/:username"       => "users#show_detailed",   :as => :show_user, :constraints => username_h
  get   "user/:username/edit"  => "users#edit_detailed",   :as => :edit_user, :constraints => username_h
  put   "user/:id/update"      => "users#update_detailed", :as => :update_user
  get   "user/:username/bans"  => "bans#index",            :as => :bans_history, :constraints => username_h
  get   "user/:username/unban" => "bans#unban",            :as => :unban_user, :constraints => username_h
  
  get   "messages"         => "messages#index",  :as => :messages
  get   "messages/sent"    => "messages#outbox", :as => :sent_messages
  get   "message/:id"      => "messages#show",   :as => :show_message
  get   "messages/new"     => "messages#new",    :as => :new_message
  post  "messages/create"  => "messages#create", :as => :create_message
  get   "message/:id/read" => "messages#toggle", :as => :toggle_message
  
  get   "poll/:id"                        => "polls#show",   :as => :show_poll
  get   "polls/new"                       => "polls#new",    :as => :new_poll
  post  "polls/create"                    => "polls#create", :as => :create_poll 
  post  "poll/:id/choice/:choice_id/vote" => "polls#vote",   :as => :vote

  get   "admin" => "admin#index", :as => :admin
  
  get   "warnings/new"    => "warnings#new",    :as => :new_warning
  post  "warnings/create" => "warnings#create", :as => :create_warning
  
  get   "bans"                 => "bans#index",  :as => :bans
  get   "bans/new(/:username)" => "bans#new",    :as => :new_ban, :constraints => username_h
  post  "bans/create"          => "bans#create", :as => :create_ban

  get   "sessions" => "sessions#index",  :as => :sessions

  get   "settings"        => "settings#index",  :as => :settings
  put   "settings/update" => "settings#update", :as => :update_settings
  
  get   "announcements"            => "announcements#index",   :as => :announcements
  get   "announcements/new"        => "announcements#new",     :as => :new_announcement
  post  "announcements/create"     => "announcements#create",  :as => :create_announcement
  get   "announcement/:id/edit"    => "announcements#edit",    :as => :edit_announcement
  put   "announcement/:id/update"  => "announcements#update",  :as => :update_announcement
  get   "announcement/:id/destroy" => "announcements#destroy", :as => :destroy_announcement
  get   "announcement/:id/toggle"  => "announcements#toggle",  :as => :toggle_announcement
  
  get   "icons"        => "icons#index",   :as => :icons
  post  "icons/create" => "icons#create",  :as => :create_icon
  get   "icon/destroy" => "icons#destroy", :as => :destroy_icon
  
  get   "smilies"        => "smilies#index",   :as => :smilies
  post  "smilies/create" => "smilies#create",  :as => :create_smiley
  get   "smiley/destroy" => "smilies#destroy", :as => :destroy_smiley
  
  get   "smilies-and-bbcode" => "misc#smilies", :as => :smilies_and_bbcode
  get   "stats"              => "misc#stats",   :as => :stats
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipient, :class_name => 'User'

  validates :subject, :presence => true, :length => { :maximum => 50 }
  validates :body, :presence => true
  
  default_scope order('id desc')
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :logged_in_only
  
  helper_method :your_pm?
  
  def index
    @messages = current_user.received_messages.includes(:user).page(params[:page]).per(20)
  end
    
  def outbox
    @messages = current_user.messages.includes(:recipient).page(params[:page]).per(20)
  end
  
  def show
    @message = Message.find(params[:id])
    if your_pm?(@message) || @message.user_id == current_user.id
      @message_sender = @message.user.username
      if your_pm?(@message) && !@message.read?
        @message.update_attribute(:read, true)
      end
    else
      render NOT_ENOUGH_RIGHTS
    end
  end
  
  def new
    if can_pm
      @message = Message.new
      if params[:reply]
        @reply = Message.find(params[:reply])
        if your_pm?(@reply)
          @message.subject = "#{'Re: ' unless @reply.subject =~ /^Re:/i}#{@reply.subject}"
          @message.body = "\n\n\n#{'-'*41}\nOriginal Message:\n#{@reply.body}"
        else
          render NOT_ENOUGH_RIGHTS
        end
      end
    else
      render NOT_ENOUGH_RIGHTS
    end
  end
  
  def create
    @recipient = User.find_by_username(params[:message][:recipient])
    if @recipient.nil?
      flash[:error] = "User does not exist"
      params[:message][:recipient] = nil
      @message = current_user.messages.new(params[:message])
      render :new
    else
      @message = current_user.messages.new(:recipient_id => @recipient.id,
        :subject  => params[:message][:subject],
        :body     => params[:message][:body],
        :ip       => request.remote_ip)
      if @message.save
        redirect_to sent_messages_path
      else
        render :new
      end
    end
  end
  
  def toggle
    @message = current_user.received_messages.find(params[:id])
    @message.update_attribute(:read, !@message.read?)
    redirect_to messages_path
  end
  
  private
  
  def your_pm?(message)
    message.recipient_id == current_user.id
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def pm
    pm_count = current_user.received_messages.where("`messages`.read = ?", false).size
    pm_link = link_to 'PM', messages_path
    if pm_count > 0
      %{<span class="bold coloryellow">#{pm_count} #{image_tag('icons/new.gif')} #{pm_link}</span>}.html_safe
    else
      pm_link
    end
  end
end

app/views/messages/_list_messages.html.erb
<div class="list">
  <table>
    <tr>
      <th style="width:20%"><%= type == 'inbox' ? 'From' : 'To' %></th>
      <th style="width:45%">Subject</th>
      <th style="width:20%">Date</th>
      <th style="width:15%">Action</th>
    </tr>
  <% @messages.each do |message| %>
    <tr class="<%= cyclize %><%= ' bold' if !message.read? && type == 'inbox' %>">
      <td><%= link_to u = (type == 'inbox' ? message.user : message.recipient).username, show_profile_path(:username => u) %></td>
      <td><%= link_to message.subject, show_message_path(message) %></td>
      <td><%= message.created_at.strftime('%m/%d/%g %H:%M') %></td>
      <td><%= link_to 'Mark ' + (message.read? ? 'Unread' : 'Read'), toggle_message_path(message) if type == 'inbox' %></td>
    </tr>
  <% end %>
  </table>
</div>
<div class="alignright" style="margin-top: 5px"><%= paginate @messages %></div>

app/views/messages/_mykpf_sidebar.html.erb
<ul>
  <li><%= link_to_unless_current 'Inbox', messages_path %></li>
  <li><%= link_to_unless_current 'Sent', sent_messages_path %></li>
<% if can_pm%>
  <li><%= link_to_unless_current 'New PM', new_message_path %></li>
<% end %>
</ul>

app/views/messages/index.html.erb
<% title 'Inbox' %>
<div class="mykpf">
  <table>
    <tr>
      <td class="mykpf-sidebar">
        <%= render 'mykpf_sidebar' %>
      </td>
      <td>
        <%= render 'list_messages', :type => 'inbox' %>
      </td>
    </tr>
  </table>
</div>

app/views/messages/new.html.erb
<% title 'New Private Message' %>
<div class="mykpf">
  <table>
    <tr>
      <td class="mykpf-sidebar">
        <%= render 'mykpf_sidebar' %>
      </td>
      <td>
        <div class="form">
          <%= form_for @message, :as => :message, :url => create_message_path do |f| %>
            <table>
              <tr>
                <td>To</td>
                <td><%= f.text_field :recipient, :value => params[:recipient] %></td>
              </tr>
              <tr>
                <td>Subject</td>
                <td><%= f.text_field :subject, :maxlength => 50, :size => 30 %></td>
              </tr>
              <tr>
                <td style="vertical-align: top">Message</td>
                <td><%= f.text_area :body %></td>
              </tr>
              <tr>
                <td><%= submit_tag 'Send Message' %></td>
                <td><%= link_to "Smilies and BBcode", smilies_and_bbcode_path, :target => "_blank" %></td>
              </tr>
            </table>
          <% end %>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/messages/outbox.html.erb
<% title 'Sent Messages' %>
<div class="mykpf">
  <table>
    <tr>
      <td class="mykpf-sidebar">
        <%= render 'mykpf_sidebar' %>
      </td>
      <td>
        <%= render 'list_messages', :type => 'sent' %>
      </td>
    </tr>
  </table>
</div>

app/views/messages/show.html.erb
<% title 'Reading Message' %>
<div class="mykpf">
  <table>
    <tr>
      <td class="mykpf-sidebar">
        <%= render 'mykpf_sidebar' %>
      </td>
      <td>
        <table class="pm-headers size13">
          <tr>
            <td><%= t = (@message_sender == current_user.username ? 'To:' : 'From:') %></td>
            <td>
              <%= t == 'To:' ? @message.recipient.username :
                link_to(@message_sender, new_message_path(:recipient => @message_sender)) %>
              <span class="size11">
                [
                  <%= @message.user.posts.size %> Posts |
                  <%= link_to "View Profile", show_profile_path(:username => @message_sender) %>
                  <%=raw "| " + link_to("User Info", show_user_path(:username => @message_sender)) if is_staff? %>
                ]
              </span>
            </td>
          </tr>
          <tr>
            <td>Subject:</td>
            <td><%= @message.subject %></td>
          </tr>
          <tr>
            <td>Date:</td>
            <td><%= @message.created_at.strftime("%B %d %Y %H:%M") %></td>
          </tr>
        </table>
      
        <div class="pm-body bglightgray size13">
          <%= bb @message.body %>
        </div>
        
        &nbsp;<%= link_to 'Reply', new_message_path(:recipient => @message_sender, :reply => @message.id) if can_pm && your_pm?(@message) %>
      </td>
    </tr>
  </table>
</div>