config/routes.rb
TLF::Application.routes.draw do
  username_h = { :username => %r([^/]+) }
  
  root :to => "forums#index"
  
  get   "search" => "forums#search", :as => :search
  
  get   "forums"                 => "admin#forums",   :as => :forums
  post  "forums/sort"            => "forums#sort",    :as => :sort_forums
  get   "forum/:id(/page/:page)" => "forums#show",    :as => :show_forum
  get   "forums/new"             => "forums#new",     :as => :new_forum  
  post  "forums/create"          => "forums#create",  :as => :create_forum
  get   "forum/:id/edit"         => "forums#edit",    :as => :edit_forum
  put   "forum/:id/update"       => "forums#update",  :as => :update_forum
  match "forum/:id/destroy"      => "forums#destroy", :as => :destroy_forum
  
  get   "thread/:id(/page/:page)"       => "threads#show",    :as => :show_thread
  get   "forum/:forum_id/thread/new"    => "threads#new",     :as => :new_thread
  post  "forum/:forum_id/thread/create" => "threads#create",  :as => :create_thread
  get   "thread/:id/edit"               => "threads#edit",    :as => :edit_thread
  put   "thread/:id/update"             => "threads#update",  :as => :update_thread
  get   "thread/:id/destroy"            => "threads#destroy", :as => :destroy_thread

  get   "posts(/:username(/page/:page))"             => "posts#index",   :as => :posts  
  get   "thread/:thread_id/post/new(/quote/:sub_id)" => "posts#new",     :as => :new_post
  post  "thread/:thread_id/post/create"              => "posts#create",  :as => :create_post
  get   "thread/:thread_id/post/:id/edit"            => "posts#edit",    :as => :edit_post
  put   "thread/:thread_id/post/:id/update"          => "posts#update",  :as => :update_post
  get   "post/:id/destroy"                           => "posts#destroy", :as => :destroy_post
  get   "post/:id/nuke"                              => "posts#nuke",    :as => :nuke_post

  get   "register"               => "users#new",               :as => :new_user
  post  "users/create"           => "users#create",            :as => :create_user
  get   "user/:id/activate/:key" => "users#activate",          :as => :activate_user
  match "request_password"       => "users#request_password",  :as => :request_password
  get   "user/:id/recover/:key"  => "users#recover_password",  :as => :recover_password
  get   "user/:id/resend"        => "users#resend_activation", :as => :resend_activation
  
  match "login"  => "sessions#new",     :as => :login
  get   "logout" => "sessions#destroy", :as => :logout

  get   "profile/:username" => "users#show",   :as => :show_profile, :constraints => username_h
  get   "myprofile/edit"    => "users#edit",   :as => :edit_profile
  put   "myprofile/update"  => "users#update", :as => :update_profile

  get   "users"                => "users#index",           :as => :users
  get   "user/:username"       => "users#show_detailed",   :as => :show_user, :constraints => username_h
  get   "user/:username/edit"  => "users#edit_detailed",   :as => :edit_user, :constraints => username_h
  put   "user/:id/update"      => "users#update_detailed", :as => :update_user
  get   "user/:username/bans"  => "bans#index",            :as => :bans_history, :constraints => username_h
  get   "user/:username/unban" => "bans#unban",            :as => :unban_user, :constraints => username_h
  
  get   "messages"         => "messages#index",  :as => :messages
  get   "messages/sent"    => "messages#outbox", :as => :sent_messages
  get   "message/:id"      => "messages#show",   :as => :show_message
  get   "messages/new"     => "messages#new",    :as => :new_message
  post  "messages/create"  => "messages#create", :as => :create_message
  get   "message/:id/read" => "messages#toggle", :as => :toggle_message
  
  get   "poll/:id"                        => "polls#show",   :as => :show_poll
  get   "polls/new"                       => "polls#new",    :as => :new_poll
  post  "polls/create"                    => "polls#create", :as => :create_poll 
  post  "poll/:id/choice/:choice_id/vote" => "polls#vote",   :as => :vote

  get   "admin" => "admin#index", :as => :admin
  
  get   "warnings/new"    => "warnings#new",    :as => :new_warning
  post  "warnings/create" => "warnings#create", :as => :create_warning
  
  get   "bans"                 => "bans#index",  :as => :bans
  get   "bans/new(/:username)" => "bans#new",    :as => :new_ban, :constraints => username_h
  post  "bans/create"          => "bans#create", :as => :create_ban

  get   "sessions" => "sessions#index",  :as => :sessions

  get   "settings"        => "settings#index",  :as => :settings
  put   "settings/update" => "settings#update", :as => :update_settings
  
  get   "announcements"            => "announcements#index",   :as => :announcements
  get   "announcements/new"        => "announcements#new",     :as => :new_announcement
  post  "announcements/create"     => "announcements#create",  :as => :create_announcement
  get   "announcement/:id/edit"    => "announcements#edit",    :as => :edit_announcement
  put   "announcement/:id/update"  => "announcements#update",  :as => :update_announcement
  get   "announcement/:id/destroy" => "announcements#destroy", :as => :destroy_announcement
  get   "announcement/:id/toggle"  => "announcements#toggle",  :as => :toggle_announcement
  
  get   "icons"        => "icons#index",   :as => :icons
  post  "icons/create" => "icons#create",  :as => :create_icon
  get   "icon/destroy" => "icons#destroy", :as => :destroy_icon
  
  get   "smilies"        => "smilies#index",   :as => :smilies
  post  "smilies/create" => "smilies#create",  :as => :create_smiley
  get   "smiley/destroy" => "smilies#destroy", :as => :destroy_smiley
  
  get   "smilies-and-bbcode" => "misc#smilies", :as => :smilies_and_bbcode
  get   "stats"              => "misc#stats",   :as => :stats
end

app/models/ban.rb
class Ban < ActiveRecord::Base
  belongs_to :user
  belongs_to :banner, :class_name => 'User'
  belongs_to :post
  
  after_create :add_ban_to_user
  
  private
  
  def add_ban_to_user
    user.ban
  end
end

app/controllers/bans_controller.rb
class BansController < ApplicationController
  before_filter :mods_only, :except => [:index]
  
  def index
    if params[:username]
      @user = User.find_by_username(params[:username])
      if @user
        bans = @user.bans.order('id desc')
        @title = "Ban History for #{@user.username} (#{bans.size})"
      else
        flash[:error] = "User does not exist"
        redirect_to :back
      end
    else
      if params[:type].blank?
        bans = Ban.where('permanent = false AND expires_at > ?', Time.now).order('expires_at asc')
      elsif params[:type] == 'perm'
        bans = Ban.where(:permanent => true).order('id desc')
      end
      @title = "List of " + (params[:type].blank? ? 'Temp' : 'Perm') + " Bans (#{bans.size})"
    end
    @bans = bans.includes(:user).includes(:banner).includes(:post).page(params[:page]).per(50)
  end
  
  def create
    user = User.find_by_username(params[:ban][:username])
    if user.nil?
      flash[:error] = "User does not exist"
      redirect_to new_ban_path
    else
      user.unban if user.bans.last
      t = Time.now
      dur_hash = {:'2 days' => t+2.days, :'1 week' => t+1.week, :'2 weeks' => t+2.weeks,
        :'30 days' => t+30.days, :'60 days' => t+60.days, :'90 days' => t+90.days, :Permanent => ''}
      duration = dur_hash[params[:ban][:duration].to_sym]
      post_duration = duration.present? ? "temp banned for #{params[:ban][:duration]}" : "banned"
      reason = params[:ban][:reason] == 'other' ? params[:ban][:other_reason] : params[:ban][:reason]
      @thread = Topic.find(settings.ban_thread)
      @ban = user.bans.new(:banner_id => current_user.id,
        :post_id    => (params[:post_id] if params[:post_ban]),
        :duration   => params[:ban][:duration],
        :reason     => reason,
        :permanent  => (duration.blank?),
        :expires_at => (duration.blank? ? t : duration))
      @post = @thread.posts.new(:sub_id => (@thread.posts.last.sub_id+1),
        :user_id => settings.bot_id,
        :body    => "[b]#{user.username}[/b] was just [b]#{post_duration}[/b] by #{current_user.username}.\n\nThat account was created on [b]#{user.created_at.strftime("%B %d %Y %H:%M")}[/b] and had [b]#{user.posts.count.to_s}[/b] posts.\n\n[b]Reason:[/b] #{reason}",
        :ip      => request.remote_ip)
      if user.ban && @ban.save && @post.save && @thread.update_attribute(:title, "Automated Ban List [Latest: #{user.username}]")
        if params[:post_ban]
          post = Post.find(params[:post_id])
          post.ban!(:temporary => duration.present?)
          redirect_to show_thread_path(post.topic_id, :page => params[:page])
        else
          redirect_to show_user_path(:username => params[:ban][:username])
        end
      else
        redirect_to new_ban_path
      end
    end
  end
  
  def unban
    @user = User.find_by_username(params[:username])
    @user.unban if @user
    redirect_to :back
  end
end

app/views/bans/index.html.erb
<% title @title %>
<%= render 'shared/staff_menu' %>
<div class="alignright">
  <%= link_to('New', new_ban_path) + "&nbsp;".html_safe if is_mod? %>
  <%= link_to 'Permanent Bans', bans_path(:type => 'perm') if params[:type].blank? %>
  <%= link_to 'Temporary Bans', bans_path if params[:type] %>
</div>
<div class="list">
  <table>
    <tr>
      <th>Username</th>
      <th>Banned By</th>
      <th>Banned On</th>
      <th>Unbanned On</th>
      <th>Duration</th>
    <% if is_mod? %>
      <th></th>
    <% end %>
      <th></th>
    </tr>
  <% @bans.each do |ban| %>
    <tr class="<%= c = cyclize %>">
      <td>
        <%= link_to (u = ban.user).styled_name, show_user_path(:username => u.username) %><br>
        <span class="size11">
          Banned <%= link_to_unless_current b = ban.user.bans.size, bans_history_path(:username => u.username) %>
          Time<%= b == 1 ? "" : "s" %>
        </span>
      </td>
      <td>
        <%= link_to (u = ban.banner).styled_name, show_user_path(:username => u.username) %><br>
        <span class="size11">Banned <%= pluralize(Ban.where(:banner_id => ban.banner_id).size, 'User') %></span>
      </td>
      <td><%= ban.created_at.strftime("%B %d %Y %H:%M") %></td>
      <td><%= ban.permanent? ? 'Never' : ban.expires_at.strftime("%B %d %Y %H:%M") %></td>
      <td><%= ban.duration %></td>
    <% if is_mod? %>
      <td><%= link_to 'Unban', unban_user_path(:username => ban.user.username) %></td>
    <% end %>
      <td><%= link_to '+', '#', :class => 'monospace', :title => 'Show ban reason', "data-ban" => ban.id %></td>
    </tr>
    <tr id="ban_reason_<%= ban.id %>" style="display:none">
      <td colspan="<%= is_mod? ? '7': '6' %>" style="border-top:0;padding-bottom:8px" class="<%= c %>">
        <strong>Reason:</strong> <%= bb ban.reason, :html => true  %>
      <% if ban.post %>
        <br><%= bb "[quote]User was banned for this post: ([url=#{show_thread_path(ban.post.topic_id, :page => ban.post.page, :anchor => ban.post.sub_id)}]Direct Link[/url])\n\n#{ban.post.body}[/quote]", :smilies => ban.post.smilies, :html => ban.post.html %>
      <% end %>
      </td>
    </tr>
  <% end %>
  </table>
</div>
<script>
$("a[data-ban]").click(function() {
    if ($(this).text() == "+") {
        $(this).text("-");
    } else {
        $(this).text("+");
    }
    var ban_id = $(this).attr("data-ban");
    $("tr#ban_reason_" + ban_id).toggle();
    return false;
})
</script>

app/views/bans/new.html.erb
<% title 'New Ban' %>
<%= render 'shared/staff_menu' %>
<div class="form">
  <%= form_for :ban, :url => create_ban_path(:post_id => params[:post_id], :page => params[:page]) do |f| %>
    <table>
      <tr>
        <td>Username:</td>
        <td><%= f.text_field :username, :value => params[:username] %></td>
      <tr>
        <td>Duration:</td>
        <td><%= f.select :duration, ["2 days", "1 week", "2 weeks", "30 days", "60 days", "90 days", "Permanent"] %></td>
      </tr>
      <tr>
        <td style="vertical-align: top">Reason:</td>
        <td>
          <%= f.radio_button :reason, 'I have my reasons.' %> I have my reasons.<br />
          <%= f.radio_button :reason, 'Previously banned user.' %> Previously banned user.<br />
          <%= f.radio_button :reason, 'Malicious user.' %> Malicious user.<br />
          <%= f.radio_button :reason, 'Advertising.' %> Advertising.<br />
          <%= f.radio_button :reason, 'Spammer.' %> Spammer.<br />
          <%= f.radio_button :reason, 'other', :checked => true %> Other (only works if selected):<br />
          <%= f.text_area :other_reason %>
        </td>
      </tr>
      <tr>
        <td><%= submit_tag "Ban!" %></td>
        <td>
        <% if params[:post_id] %>
          Leave ban notice for Post #<%= params[:post_id] %> <%= check_box_tag :post_ban, true, true %>
        <% end %>
        </td>
      </tr>
    </table>
    <% end %>
</div>